<?php
/* @var $block \Sga\Configview\Block\Adminhtml\System\Popin */
if ($block->isEnabled()) :
    $config = [
        'elements' => [
            'popin' => '#configview_popin',
            'popin_close' => '#configview_popin .close',
            'popin_container' => '#configview_popin_container',
            'form_elements' => '#config-edit-form fieldset.config td.value input[type=text], #config-edit-form fieldset.config td.value select, #config-edit-form fieldset.config td.value textarea'
        ],
        'urls' => [
            'load_rewrite' => $block->getUrlBuilder()->getUrl('configview/system/loadRewrite'),
            'load_popin' => $block->getUrlBuilder()->getUrl('configview/system/loadPopin')
        ]
    ];
?>
<div id="configview_popin" style="display:none">
    <div>
        <a href="javascript:void(0)" class="close"><?= __('Close') ?></a>
        <div id="configview_popin_container"></div>
    </div>
</div>

<script type="text/x-magento-init">
{"#configview_popin": {"Sga_Configview/js/system": <?= $block->getJsonSerializer()->serialize($config) ?>}}
</script>
<?php endif ?>