<?php
/* @var $this Sga\Configview\Block\Adminhtml\Catalog\Product\Popin */
$defaultValue = $this->getDefaultValue();
?>
<div class="show-in">
    <ul>
        <li>
            <label><?= __('Attribute Code') ?> :</label>
            <?= $this->getAttributeCode() ?>
        </li>
    </ul>
</div>

<div class="default">
    <label><a href="<?php echo $this->getUrlBuilder()->getUrl('catalog/product/edit', ['id' => $this->getCurrentProductId()]) ?>"><?= __('Default') ?></a></label> : <?php echo $defaultValue !== null ? htmlentities($defaultValue) : '<span>NULL</span>' ?>
</div>

<?php foreach($this->getStoreManager()->getStores() as $store): ?>
    <?php
    $website = $store->getWebsite();
    $storeValue = $this->getStoreValue($store->getId());
    ?>
    <ul class="scopes">
        <li><label><?php echo $website->getName().' > ' ?><a href="<?php echo $this->getUrlBuilder()->getUrl('catalog/product/edit', ['id' => $this->getCurrentProductId(), 'store' => $store->getId()]) ?>"><?php echo $store->getName() ?></a></label> : <?php echo $storeValue !== null ? htmlentities($storeValue) : '<span>NULL</span>' ?></li>
    </ul>
<?php endforeach ?>